### ISSUE TITLE
Can't work on the web.

### ISSUE THREAD

**Issue by nattapatwakhet** [MiroslavZB/world-time#4]
Launching lib/main.dart on Chrome in debug mode...
Warning: In index.html:14: Local variable for "serviceWorkerVersion" is deprecated. Use "{{flutter_service_worker_version}}" template token instead.
Warning: In index.html:175: "FlutterLoader.loadEntrypoint" is deprecated. Use "FlutterLoader.load" instead.
Warning: In index.html:186: "FlutterLoader.loadEntrypoint" is deprecated. Use "FlutterLoader.load" instead.
org-dartlang-app:/web_plugin_registrant.dart:28:8: Error: Error when reading '../../../../.pub-cache/hosted/pub.dev/thai_id_card_numbers-1.2.1/lib/thai_id_card_numbers_web.dart': No such file or directory
import 'package:thai_id_card_numbers/thai_id_card_numbers_web.dart';
       ^
org-dartlang-app:/web_plugin_registrant.dart:54:3: Error: Undefined name 'ThaiIdCardNumbersWeb'.
  ThaiIdCardNumbersWeb.registerWith(registrar);
  ^^^^^^^^^^^^^^^^^^^^
org-dartlang-app:/web_plugin_registrant.dart:56:3: Error: Undefined name 'WorldtimePlugin'.
  WorldtimePlugin.registerWith(registrar);
  ^^^^^^^^^^^^^^^
Failed to compile application.

Exited (1).

**Comment by MiroslavZB** [comment]
Hi, are you sure that this issue is coming from worldtime? we don't define `ThaiIdCardNumbers` nor does the worldtime plugin depend on thai_id_card_numbers

**Comment by jeevanwst** [comment]
Hi @MiroslavZB, I'm getting same issue on web platform. 

Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...
org-dartlang-app:/web_plugin_registrant.dart:60:3: Error: Undefined name 'WorldtimePlugin'.
  WorldtimePlugin.registerWith(registrar);
  ^^^^^^^^^^^^^^^
Failed to compile application.

**Comment by MiroslavZB** [comment]
> Hi @MiroslavZB, I'm getting same issue on web platform. 
> 
> Launching lib/main.dart on Chrome in debug mode...
> Waiting for connection from debug service on Chrome...
> org-dartlang-app:/web_plugin_registrant.dart:60:3: Error: Undefined name 'WorldtimePlugin'.
>   WorldtimePlugin.registerWith(registrar);
>   ^^^^^^^^^^^^^^^
> Failed to compile application.

@jeevanwst did you try:
`flutter pub clean` and `flutter pub get`

**Comment by jeevanwst** [comment]
@MiroslavZB yes, getting same issue

**Comment by jeevanwst** [comment]
> > Hi @MiroslavZB, I'm getting same issue on web platform.
> > Launching lib/main.dart on Chrome in debug mode...
> > Waiting for connection from debug service on Chrome...
> > org-dartlang-app:/web_plugin_registrant.dart:60:3: Error: Undefined name 'WorldtimePlugin'.
> > WorldtimePlugin.registerWith(registrar);
> > ^^^^^^^^^^^^^^^
> > Failed to compile application.
> 
> @jeevanwst did you try: `flutter pub clean` and `flutter pub get`

@MiroslavZB yes, still getting same issue

**Comment by MiroslavZB** [comment]
> > > Hi @MiroslavZB, I'm getting same issue on web platform.
> > > Launching lib/main.dart on Chrome in debug mode...
> > > Waiting for connection from debug service on Chrome...
> > > org-dartlang-app:/web_plugin_registrant.dart:60:3: Error: Undefined name 'WorldtimePlugin'.
> > > WorldtimePlugin.registerWith(registrar);
> > > ^^^^^^^^^^^^^^^
> > > Failed to compile application.
> > 
> > @jeevanwst did you try: `flutter pub clean` and `flutter pub get`
> 
> @MiroslavZB yes, still getting same issue
> 

@jeevanwst here are a few other things you can try:
1. https://stackoverflow.com/a/63232647
2. Running the Flutter config command to enable web support 
3. Removing the plugin and adding it again 
4. Can you give me the output of 
`flutter doctor`

**Comment by jeevanwst** [comment]
> 1. https://stackoverflow.com/a/63232647



> > > > Hi @MiroslavZB, I'm getting same issue on web platform.
> > > > Launching lib/main.dart on Chrome in debug mode...
> > > > Waiting for connection from debug service on Chrome...
> > > > org-dartlang-app:/web_plugin_registrant.dart:60:3: Error: Undefined name 'WorldtimePlugin'.
> > > > WorldtimePlugin.registerWith(registrar);
> > > > ^^^^^^^^^^^^^^^
> > > > Failed to compile application.
> > > 
> > > 
> > > @jeevanwst did you try: `flutter pub clean` and `flutter pub get`
> > 
> > 
> > @MiroslavZB yes, still getting same issue
> 
> @jeevanwst here are a few other things you can try:
> 
> 1. https://stackoverflow.com/a/63232647
> 2. Running the Flutter config command to enable web support
> 3. Removing the plugin and adding it again
> 4. Can you give me the output of
>    `flutter doctor`

jeevan@Jeevans-MacBook-Pro occser-frontend % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.27.1, on macOS 15.0.1 24A348 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.2)
[✓] Connected device (8 available)
[✓] Network resources

• No issues found!

**Comment by distatk** [comment]
I also have this issue, however I think I might fixed it

I created `lib/src/worldtime_web.dart` as a placeholder for web implementation
```
import 'dart:async';

import 'package:flutter/services.dart';
import 'package:flutter_web_plugins/flutter_web_plugins.dart';

// In order to *not* need this ignore, consider extracting the "web" version
// of your plugin as a separate package, instead of inlining it in the same
// package as the core of your plugin.
// ignore: avoid_web_libraries_in_flutter

/// A web implementation of the FlutterNativeSplash plugin.
class WorldtimeWebPlugin {
  static void registerWith(Registrar registrar) {
    final MethodChannel channel = MethodChannel(
      'worldtime',
      const StandardMethodCodec(),
      registrar,
    );

    final pluginInstance = WorldtimeWebPlugin();
    channel.setMethodCallHandler(pluginInstance.handleMethodCall);
  }

  Future<dynamic> handleMethodCall(MethodCall call) async {
    // nothing to implement here as we do not need any native calls
  }
}
```

I  also modified `pubspec.yaml`

```
dependencies:
  ...
  flutter_web_plugins:
    sdk: flutter

...

flutter:
  plugin:
    platforms:
      ...
      web:
        pluginClass: WorldtimeWebPlugin
        fileName: src/worldtime_web.dart
```

after these changes, I can run my project on web
